# Generated by Django 4.2 on 2023-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'This email address is already in use.'}, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('teacher', 'Teacher')], max_length=10)),
                ('studio_name', models.CharField(blank=True, max_length=100, null=True)),
                ('studio_location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
