# Generated by Django 4.2 on 2023-05-11 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
